###########################################################
# This is the Hosts YAML file.
# YAML is a human friendly data serialisation standard for all programming languages.
#
# NOTE: Any line that begins with '#' is known as a comment and will be ignored
#
# This file includes a list of all the hosts listed on the site. 
# Structure:
# 
# - name: John Smith
#   role: Cool Guy
#   image: /path/to/image.png (300px * 300px is recommended)
#   linkedin: linkedin url
#   twitter: twitter url
#   facebook: facebook url
#
# 1. Each new entry begins with '- '
# 2. Each line of the entry has a 'key' and a 'value' separated by a colon ':'
#       'name' is the key, 'John Smith' is the value
# 3. You can leave any key out and it won't show in the final page. 
#    I.e. remove 'facebook' from one of the entries will stop the facebook
#    logo appearing for that host.
###########################################################

- name: Ryan Pasi
  role: Founder/Host
  image: /img/team/Ryan.png
  linkedin: http://uk.linkedin.com/pub/ryan-pasi/6a/999/271
  
- name: Myke Hall
  role: Host
  image: /img/team/myke.jpg
  linkedin: http://uk.linkedin.com/pub/myke-hall/12/3b7/644/
  twitter: http://twitter.com/mykescotland/
  
- name: Malwina Bieniawska
  role: Host
  image: /img/team/mal.jpg
  
- name: Ian Hendry
  role: Host
  image: /img/team/Ian.jpg
  twitter: https://twitter.com/IanWalkerHendry